// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNvMB0W8LVgbQgyrx9g4UFtIEj5FuJyI',
    appId: '1:818616765979:web:14db2db3a11464c9cdf2be',
    messagingSenderId: '818616765979',
    projectId: 'kilometrosycentimos',
    authDomain: 'kilometrosycentimos.firebaseapp.com',
    storageBucket: 'kilometrosycentimos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATqw1u3rOptJ_YDDW7pvS8Hl6ZkT-3ZlA',
    appId: '1:818616765979:android:1cf8283564f9c895cdf2be',
    messagingSenderId: '818616765979',
    projectId: 'kilometrosycentimos',
    storageBucket: 'kilometrosycentimos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKaKcKE3S1G_jCX3CQDEo9yi3g9weuOE',
    appId: '1:818616765979:ios:34ef85640f7455a2cdf2be',
    messagingSenderId: '818616765979',
    projectId: 'kilometrosycentimos',
    storageBucket: 'kilometrosycentimos.firebasestorage.app',
    iosBundleId: 'com.example.kilometrosycentimos',
  );

}