name: kilometrosycentimos
description: Una aplicación Flutter para gestionar tus coches, kilómetros y gastos.
publish_to: 'none' # si no lo publicarás en pub.dev

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
